<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, DatabaseMigrations, DatabaseTransactions;

    private $adminUser;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub


    }

}
